version: "2"
services: 
  django-apache2:
    build: .
    container_name: django-apache2
    ports:
      - 80:80
    volumes: 
      - ./ConsumerAffairs:/var/www/html/ConsumerAffairs
    restart: always
    depends_on:
      - mysql
    env_file: ./django-apache2.env

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - ./mysql/:/var/lib/mysql/
    ports:
      - 3306:3306
    env_file: ./mysql.env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql

    